"""credenciales sat cfdi y reglas de validacion

Revision ID: 0e7a81f4f542
Revises: 810701cc57a5
Create Date: 2026-07-28 23:24:23.984641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e7a81f4f542'
down_revision: Union[str, None] = '810701cc57a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reglas_validacion',
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('severidad', sa.String(length=10), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reglas_validacion_codigo'), 'reglas_validacion', ['codigo'], unique=True)
    op.create_table('cfdis',
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('uuid_fiscal', sa.String(length=36), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('direccion', sa.String(length=10), nullable=False),
    sa.Column('rfc_emisor', sa.String(length=13), nullable=False),
    sa.Column('nombre_emisor', sa.String(length=255), nullable=False),
    sa.Column('rfc_receptor', sa.String(length=13), nullable=False),
    sa.Column('nombre_receptor', sa.String(length=255), nullable=False),
    sa.Column('forma_pago_codigo', sa.String(length=5), nullable=True),
    sa.Column('uso_cfdi_codigo', sa.String(length=5), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('iva', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('estatus', sa.String(length=15), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cfdis_empresa_id'), 'cfdis', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_cfdis_fecha'), 'cfdis', ['fecha'], unique=False)
    op.create_index(op.f('ix_cfdis_rfc_emisor'), 'cfdis', ['rfc_emisor'], unique=False)
    op.create_index(op.f('ix_cfdis_rfc_receptor'), 'cfdis', ['rfc_receptor'], unique=False)
    op.create_index(op.f('ix_cfdis_uuid_fiscal'), 'cfdis', ['uuid_fiscal'], unique=True)
    op.create_table('credenciales_sat',
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('conectado_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credenciales_sat_empresa_id'), 'credenciales_sat', ['empresa_id'], unique=True)
    op.create_table('cfdi_alertas',
    sa.Column('cfdi_id', sa.Uuid(), nullable=False),
    sa.Column('regla_codigo', sa.String(length=50), nullable=False),
    sa.Column('severidad', sa.String(length=10), nullable=False),
    sa.Column('detalle', sa.String(length=500), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cfdi_id'], ['cfdis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cfdi_alertas_cfdi_id'), 'cfdi_alertas', ['cfdi_id'], unique=False)
    op.create_table('cfdi_conceptos',
    sa.Column('cfdi_id', sa.Uuid(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('unidad_codigo', sa.String(length=10), nullable=True),
    sa.Column('valor_unitario', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('importe', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['cfdi_id'], ['cfdis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cfdi_conceptos_cfdi_id'), 'cfdi_conceptos', ['cfdi_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cfdi_conceptos_cfdi_id'), table_name='cfdi_conceptos')
    op.drop_table('cfdi_conceptos')
    op.drop_index(op.f('ix_cfdi_alertas_cfdi_id'), table_name='cfdi_alertas')
    op.drop_table('cfdi_alertas')
    op.drop_index(op.f('ix_credenciales_sat_empresa_id'), table_name='credenciales_sat')
    op.drop_table('credenciales_sat')
    op.drop_index(op.f('ix_cfdis_uuid_fiscal'), table_name='cfdis')
    op.drop_index(op.f('ix_cfdis_rfc_receptor'), table_name='cfdis')
    op.drop_index(op.f('ix_cfdis_rfc_emisor'), table_name='cfdis')
    op.drop_index(op.f('ix_cfdis_fecha'), table_name='cfdis')
    op.drop_index(op.f('ix_cfdis_empresa_id'), table_name='cfdis')
    op.drop_table('cfdis')
    op.drop_index(op.f('ix_reglas_validacion_codigo'), table_name='reglas_validacion')
    op.drop_table('reglas_validacion')
    # ### end Alembic commands ###
