"""cfdi serie folio metodo pago version

Revision ID: 2f605958da04
Revises: bbc8f2b8cd96
Create Date: 2026-08-18 12:56:38.218547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f605958da04'
down_revision: Union[str, None] = 'bbc8f2b8cd96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cfdis', sa.Column('version', sa.String(length=5), nullable=True))
    op.add_column('cfdis', sa.Column('serie', sa.String(length=25), nullable=True))
    op.add_column('cfdis', sa.Column('folio', sa.String(length=40), nullable=True))
    op.add_column('cfdis', sa.Column('metodo_pago_codigo', sa.String(length=5), nullable=True))
    op.create_index(op.f('ix_cfdis_folio'), 'cfdis', ['folio'], unique=False)
    op.create_index(op.f('ix_cfdis_metodo_pago_codigo'), 'cfdis', ['metodo_pago_codigo'], unique=False)
    # ### end Alembic commands ###

    # Backfill de los CFDIs ya existentes (todos simulados): versión 4.0, método
    # derivado de la forma de pago ("99 por definir" => PPD), serie por dirección
    # y folio consecutivo por empresa/dirección en orden cronológico.
    op.execute("UPDATE cfdis SET version = '4.0' WHERE version IS NULL")
    op.execute(
        """
        UPDATE cfdis
        SET metodo_pago_codigo = CASE WHEN forma_pago_codigo = '99' THEN 'PPD' ELSE 'PUE' END
        WHERE metodo_pago_codigo IS NULL AND tipo IN ('ingreso', 'egreso')
        """
    )
    op.execute(
        """
        UPDATE cfdis SET serie = CASE WHEN direccion = 'emitido' THEN 'A' ELSE 'F' END
        WHERE serie IS NULL
        """
    )
    op.execute(
        """
        UPDATE cfdis SET folio = sub.rn::text
        FROM (
            SELECT id, row_number() OVER (PARTITION BY empresa_id, direccion ORDER BY fecha, created_at) AS rn
            FROM cfdis
        ) AS sub
        WHERE cfdis.id = sub.id AND cfdis.folio IS NULL
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cfdis_metodo_pago_codigo'), table_name='cfdis')
    op.drop_index(op.f('ix_cfdis_folio'), table_name='cfdis')
    op.drop_column('cfdis', 'metodo_pago_codigo')
    op.drop_column('cfdis', 'folio')
    op.drop_column('cfdis', 'serie')
    op.drop_column('cfdis', 'version')
    # ### end Alembic commands ###
