"""cfdi xml real origen tipo_comprobante retenciones y pagos relacionados

Revision ID: 5c8878793762
Revises: 6f6766e12ef3
Create Date: 2026-08-18 16:04:47.602966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c8878793762'
down_revision: Union[str, None] = '6f6766e12ef3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cfdi_pago_doctos',
    sa.Column('cfdi_pago_id', sa.Uuid(), nullable=False),
    sa.Column('uuid_relacionado', sa.String(length=36), nullable=False),
    sa.Column('serie', sa.String(length=25), nullable=True),
    sa.Column('folio', sa.String(length=40), nullable=True),
    sa.Column('num_parcialidad', sa.Integer(), nullable=True),
    sa.Column('imp_saldo_anterior', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('imp_pagado', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('imp_saldo_insoluto', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('iva_pagado', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('fecha_pago', sa.Date(), nullable=True),
    sa.Column('forma_pago_codigo', sa.String(length=5), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['cfdi_pago_id'], ['cfdis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cfdi_pago_doctos_cfdi_pago_id'), 'cfdi_pago_doctos', ['cfdi_pago_id'], unique=False)
    op.create_index(op.f('ix_cfdi_pago_doctos_uuid_relacionado'), 'cfdi_pago_doctos', ['uuid_relacionado'], unique=False)
    op.add_column('cfdis', sa.Column('tipo_comprobante', sa.String(length=1), nullable=True))
    op.add_column('cfdis', sa.Column('fecha_timbrado', sa.DateTime(timezone=True), nullable=True))
    op.add_column('cfdis', sa.Column('origen', sa.String(length=10), server_default='mock', nullable=False))
    op.add_column('cfdis', sa.Column('xml', sa.Text(), nullable=True))
    op.add_column('cfdis', sa.Column('iva_retenido', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False))
    op.add_column('cfdis', sa.Column('isr_retenido', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False))
    op.alter_column('cfdis', 'tipo',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=15),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cfdis', 'tipo',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_column('cfdis', 'isr_retenido')
    op.drop_column('cfdis', 'iva_retenido')
    op.drop_column('cfdis', 'xml')
    op.drop_column('cfdis', 'origen')
    op.drop_column('cfdis', 'fecha_timbrado')
    op.drop_column('cfdis', 'tipo_comprobante')
    op.drop_index(op.f('ix_cfdi_pago_doctos_uuid_relacionado'), table_name='cfdi_pago_doctos')
    op.drop_index(op.f('ix_cfdi_pago_doctos_cfdi_pago_id'), table_name='cfdi_pago_doctos')
    op.drop_table('cfdi_pago_doctos')
    # ### end Alembic commands ###
