"""catalogo conceptos clave sat

Revision ID: 6f6766e12ef3
Revises: 92ca277a6b32
Create Date: 2026-08-18 15:56:39.036326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f6766e12ef3'
down_revision: Union[str, None] = '92ca277a6b32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedimento_conceptos_sat',
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('concepto', sa.String(length=255), nullable=False),
    sa.Column('concepto_norm', sa.String(length=255), nullable=False),
    sa.Column('clave_prodserv', sa.String(length=10), nullable=False),
    sa.Column('clave_unidad_sat', sa.String(length=5), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'concepto_norm', name='uq_concepto_sat_empresa')
    )
    op.create_index(op.f('ix_pedimento_conceptos_sat_empresa_id'), 'pedimento_conceptos_sat', ['empresa_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pedimento_conceptos_sat_empresa_id'), table_name='pedimento_conceptos_sat')
    op.drop_table('pedimento_conceptos_sat')
    # ### end Alembic commands ###
