"""catalogos sat

Revision ID: 810701cc57a5
Revises: 4744ad4e2f63
Create Date: 2026-07-28 23:21:25.878183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '810701cc57a5'
down_revision: Union[str, None] = '4744ad4e2f63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogos',
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tipo', 'codigo', name='uq_catalogo_tipo_codigo')
    )
    op.create_index(op.f('ix_catalogos_codigo'), 'catalogos', ['codigo'], unique=False)
    op.create_index(op.f('ix_catalogos_tipo'), 'catalogos', ['tipo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_catalogos_tipo'), table_name='catalogos')
    op.drop_index(op.f('ix_catalogos_codigo'), table_name='catalogos')
    op.drop_table('catalogos')
    # ### end Alembic commands ###
