"""conciliacion bancaria y declaraciones

Revision ID: 92ca277a6b32
Revises: 9632c0ba757e
Create Date: 2026-08-18 13:37:46.007448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92ca277a6b32'
down_revision: Union[str, None] = '9632c0ba757e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cuentas_bancarias',
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('banco', sa.String(length=60), nullable=False),
    sa.Column('alias', sa.String(length=60), nullable=False),
    sa.Column('numero', sa.String(length=30), nullable=True),
    sa.Column('moneda', sa.String(length=3), server_default='MXN', nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'alias', name='uq_cuenta_empresa_alias')
    )
    op.create_index(op.f('ix_cuentas_bancarias_empresa_id'), 'cuentas_bancarias', ['empresa_id'], unique=False)
    op.create_table('declaraciones_periodo',
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('ingresos_declarados', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('deducciones_declaradas', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('iva_declarado', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('isr_declarado', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('fecha_presentacion', sa.Date(), nullable=True),
    sa.Column('numero_operacion', sa.String(length=40), nullable=True),
    sa.Column('notas', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'anio', 'mes', name='uq_declaracion_empresa_periodo')
    )
    op.create_index(op.f('ix_declaraciones_periodo_empresa_id'), 'declaraciones_periodo', ['empresa_id'], unique=False)
    op.create_table('movimientos_bancarios',
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('cuenta_id', sa.Uuid(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('concepto', sa.String(length=300), nullable=False),
    sa.Column('referencia', sa.String(length=80), nullable=True),
    sa.Column('cargo', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('abono', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('saldo', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('huella', sa.String(length=40), nullable=False),
    sa.Column('fila_origen', sa.Integer(), nullable=True),
    sa.Column('archivo_nombre', sa.String(length=120), nullable=True),
    sa.Column('estado', sa.String(length=12), server_default='pendiente', nullable=False),
    sa.Column('cfdi_id', sa.Uuid(), nullable=True),
    sa.Column('conciliado_por', sa.String(length=10), nullable=True),
    sa.Column('nota', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cfdi_id'], ['cfdis.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuentas_bancarias.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cuenta_id', 'huella', name='uq_movimiento_cuenta_huella')
    )
    op.create_index(op.f('ix_movimientos_bancarios_cfdi_id'), 'movimientos_bancarios', ['cfdi_id'], unique=False)
    op.create_index(op.f('ix_movimientos_bancarios_cuenta_id'), 'movimientos_bancarios', ['cuenta_id'], unique=False)
    op.create_index(op.f('ix_movimientos_bancarios_empresa_id'), 'movimientos_bancarios', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_movimientos_bancarios_estado'), 'movimientos_bancarios', ['estado'], unique=False)
    op.create_index(op.f('ix_movimientos_bancarios_fecha'), 'movimientos_bancarios', ['fecha'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movimientos_bancarios_fecha'), table_name='movimientos_bancarios')
    op.drop_index(op.f('ix_movimientos_bancarios_estado'), table_name='movimientos_bancarios')
    op.drop_index(op.f('ix_movimientos_bancarios_empresa_id'), table_name='movimientos_bancarios')
    op.drop_index(op.f('ix_movimientos_bancarios_cuenta_id'), table_name='movimientos_bancarios')
    op.drop_index(op.f('ix_movimientos_bancarios_cfdi_id'), table_name='movimientos_bancarios')
    op.drop_table('movimientos_bancarios')
    op.drop_index(op.f('ix_declaraciones_periodo_empresa_id'), table_name='declaraciones_periodo')
    op.drop_table('declaraciones_periodo')
    op.drop_index(op.f('ix_cuentas_bancarias_empresa_id'), table_name='cuentas_bancarias')
    op.drop_table('cuentas_bancarias')
    # ### end Alembic commands ###
