"""vigencias fiel csd

Revision ID: 9632c0ba757e
Revises: 96d2cc1272f3
Create Date: 2026-08-18 13:14:16.371354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9632c0ba757e'
down_revision: Union[str, None] = '96d2cc1272f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credenciales_sat', sa.Column('fiel_numero_serie', sa.String(length=40), nullable=True))
    op.add_column('credenciales_sat', sa.Column('fiel_vigencia_hasta', sa.Date(), nullable=True))
    op.add_column('credenciales_sat', sa.Column('csd_numero_serie', sa.String(length=40), nullable=True))
    op.add_column('credenciales_sat', sa.Column('csd_vigencia_hasta', sa.Date(), nullable=True))
    # ### end Alembic commands ###

    # Backfill simulado para credenciales ya conectadas: FIEL próxima a vencer
    # (45 días) y CSD con 2 años — así la demo muestra el aviso de vencimiento.
    op.execute(
        """
        UPDATE credenciales_sat
        SET fiel_numero_serie = '30001000000400001234',
            fiel_vigencia_hasta = CURRENT_DATE + INTERVAL '45 days',
            csd_numero_serie = '30001000000500005678',
            csd_vigencia_hasta = CURRENT_DATE + INTERVAL '2 years'
        WHERE estado = 'conectado' AND fiel_vigencia_hasta IS NULL
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credenciales_sat', 'csd_vigencia_hasta')
    op.drop_column('credenciales_sat', 'csd_numero_serie')
    op.drop_column('credenciales_sat', 'fiel_vigencia_hasta')
    op.drop_column('credenciales_sat', 'fiel_numero_serie')
    # ### end Alembic commands ###
