"""empresa coeficiente utilidad

Revision ID: 96d2cc1272f3
Revises: 2f605958da04
Create Date: 2026-08-18 13:03:32.951844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96d2cc1272f3'
down_revision: Union[str, None] = '2f605958da04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresas', sa.Column('coeficiente_utilidad', sa.Numeric(precision=7, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empresas', 'coeficiente_utilidad')
    # ### end Alembic commands ###
