"""token version para invalidar sesiones al cambiar password

Revision ID: a9d7a6331e34
Revises: b8838431fb02
Create Date: 2026-07-29 05:25:28.444738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9d7a6331e34'
down_revision: Union[str, None] = 'b8838431fb02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('token_version', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'token_version')
    # ### end Alembic commands ###
