"""terceros clientes y proveedores

Revision ID: ace482bddcf0
Revises: 5c8878793762
Create Date: 2026-08-18 16:57:21.187799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ace482bddcf0'
down_revision: Union[str, None] = '5c8878793762'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('terceros',
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('rfc', sa.String(length=13), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('regimen_fiscal_codigo', sa.String(length=10), nullable=True),
    sa.Column('codigo_postal', sa.String(length=5), nullable=True),
    sa.Column('uso_cfdi_default', sa.String(length=5), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('contacto', sa.String(length=120), nullable=True),
    sa.Column('dias_credito', sa.Integer(), server_default='0', nullable=False),
    sa.Column('limite_credito', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('notas', sa.String(length=500), nullable=True),
    sa.Column('origen', sa.String(length=10), server_default='manual', nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'rfc', name='uq_tercero_empresa_rfc')
    )
    op.create_index(op.f('ix_terceros_empresa_id'), 'terceros', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_terceros_rfc'), 'terceros', ['rfc'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_terceros_rfc'), table_name='terceros')
    op.drop_index(op.f('ix_terceros_empresa_id'), table_name='terceros')
    op.drop_table('terceros')
    # ### end Alembic commands ###
