"""pedimentos de importacion y costo en movimientos

Revision ID: bbc8f2b8cd96
Revises: a9d7a6331e34
Create Date: 2026-08-18 12:32:39.370971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbc8f2b8cd96'
down_revision: Union[str, None] = 'a9d7a6331e34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedimentos',
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('numero', sa.String(length=10), nullable=False),
    sa.Column('patente', sa.String(length=6), nullable=False),
    sa.Column('aduana', sa.String(length=5), nullable=False),
    sa.Column('clave_pedimento', sa.String(length=5), nullable=True),
    sa.Column('tipo_operacion', sa.String(length=3), nullable=True),
    sa.Column('rfc_importador', sa.String(length=13), nullable=True),
    sa.Column('referencia', sa.String(length=60), nullable=True),
    sa.Column('fecha_entrada', sa.Date(), nullable=True),
    sa.Column('fecha_pago', sa.Date(), nullable=True),
    sa.Column('tipo_cambio', sa.Numeric(precision=12, scale=5), nullable=False),
    sa.Column('peso_bruto', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('incoterm', sa.String(length=5), nullable=True),
    sa.Column('proveedor_nombre', sa.String(length=255), nullable=True),
    sa.Column('proveedor_id_fiscal', sa.String(length=40), nullable=True),
    sa.Column('contenedores', sa.JSON(), nullable=True),
    sa.Column('guias', sa.JSON(), nullable=True),
    sa.Column('dta', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('otras_contribuciones', sa.JSON(), nullable=True),
    sa.Column('gastos_adicionales', sa.JSON(), nullable=True),
    sa.Column('utilidad', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('metodo_prorrateo', sa.String(length=20), server_default='partes_iguales', nullable=False),
    sa.Column('estatus', sa.String(length=15), server_default='borrador', nullable=False),
    sa.Column('aplicado_almacen_id', sa.Uuid(), nullable=True),
    sa.Column('origen', sa.String(length=10), server_default='m3', nullable=False),
    sa.Column('archivo_nombre', sa.String(length=120), nullable=True),
    sa.Column('notas', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aplicado_almacen_id'], ['almacenes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'aduana', 'patente', 'numero', name='uq_pedimento_empresa_aduana_patente_numero')
    )
    op.create_index(op.f('ix_pedimentos_empresa_id'), 'pedimentos', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_pedimentos_fecha_pago'), 'pedimentos', ['fecha_pago'], unique=False)
    op.create_table('pedimento_partidas',
    sa.Column('pedimento_id', sa.Uuid(), nullable=False),
    sa.Column('secuencia', sa.Integer(), nullable=False),
    sa.Column('fraccion', sa.String(length=10), nullable=False),
    sa.Column('nico', sa.String(length=4), nullable=True),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('pais_origen', sa.String(length=3), nullable=True),
    sa.Column('cantidad_umc', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('umc_clave', sa.String(length=3), nullable=False),
    sa.Column('cantidad_umt', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('umt_clave', sa.String(length=3), nullable=True),
    sa.Column('precio_unitario', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('valor_aduana', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('valor_comercial', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('valor_usd', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('igi', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('iva', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tasa_igi', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('tasa_iva', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('clave_prodserv', sa.String(length=10), nullable=True),
    sa.Column('clave_unidad_sat', sa.String(length=5), nullable=True),
    sa.Column('producto_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['pedimento_id'], ['pedimentos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pedimento_id', 'secuencia', name='uq_partida_pedimento_secuencia')
    )
    op.create_index(op.f('ix_pedimento_partidas_pedimento_id'), 'pedimento_partidas', ['pedimento_id'], unique=False)
    op.add_column('productos', sa.Column('clave_prodserv', sa.String(length=10), nullable=True))
    op.add_column('stock_movimientos', sa.Column('costo_unitario', sa.Numeric(precision=18, scale=6), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_movimientos', 'costo_unitario')
    op.drop_column('productos', 'clave_prodserv')
    op.drop_index(op.f('ix_pedimento_partidas_pedimento_id'), table_name='pedimento_partidas')
    op.drop_table('pedimento_partidas')
    op.drop_index(op.f('ix_pedimentos_fecha_pago'), table_name='pedimentos')
    op.drop_index(op.f('ix_pedimentos_empresa_id'), table_name='pedimentos')
    op.drop_table('pedimentos')
    # ### end Alembic commands ###
