"""superadmin bitacora e inventario flexible

Revision ID: c4da267b45f9
Revises: d3ae3b3de734
Create Date: 2026-07-29 00:31:02.684000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4da267b45f9'
down_revision: Union[str, None] = 'd3ae3b3de734'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bitacora',
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=True),
    sa.Column('usuario_email', sa.String(length=320), nullable=False),
    sa.Column('accion', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('entidad_tipo', sa.String(length=50), nullable=True),
    sa.Column('entidad_id', sa.String(length=64), nullable=True),
    sa.Column('metadatos', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bitacora_accion'), 'bitacora', ['accion'], unique=False)
    op.create_index(op.f('ix_bitacora_empresa_id'), 'bitacora', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_bitacora_usuario_id'), 'bitacora', ['usuario_id'], unique=False)
    op.add_column('productos', sa.Column('tipo', sa.String(length=20), server_default='producto', nullable=False))
    op.add_column('productos', sa.Column('categoria', sa.String(length=80), nullable=True))
    op.add_column('productos', sa.Column('atributos', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_productos_categoria'), 'productos', ['categoria'], unique=False)
    op.add_column(
        'usuarios',
        sa.Column('is_superadmin', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'is_superadmin')
    op.drop_index(op.f('ix_productos_categoria'), table_name='productos')
    op.drop_column('productos', 'atributos')
    op.drop_column('productos', 'categoria')
    op.drop_column('productos', 'tipo')
    op.drop_index(op.f('ix_bitacora_usuario_id'), table_name='bitacora')
    op.drop_index(op.f('ix_bitacora_empresa_id'), table_name='bitacora')
    op.drop_index(op.f('ix_bitacora_accion'), table_name='bitacora')
    op.drop_table('bitacora')
    # ### end Alembic commands ###
