"""inventario ledger

Revision ID: d3ae3b3de734
Revises: 0e7a81f4f542
Create Date: 2026-07-28 23:27:35.221405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3ae3b3de734'
down_revision: Union[str, None] = '0e7a81f4f542'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('almacenes',
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'codigo', name='uq_almacen_empresa_codigo')
    )
    op.create_index(op.f('ix_almacenes_empresa_id'), 'almacenes', ['empresa_id'], unique=False)
    op.create_table('productos',
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('unidad_codigo', sa.String(length=10), nullable=True),
    sa.Column('costo_unitario', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'sku', name='uq_producto_empresa_sku')
    )
    op.create_index(op.f('ix_productos_empresa_id'), 'productos', ['empresa_id'], unique=False)
    op.create_table('stock_movimientos',
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('producto_id', sa.Uuid(), nullable=False),
    sa.Column('almacen_id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('referencia', sa.String(length=120), nullable=True),
    sa.Column('nota', sa.String(length=255), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('cantidad <> 0', name='ck_movimiento_cantidad_no_cero'),
    sa.ForeignKeyConstraint(['almacen_id'], ['almacenes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_movimientos_almacen_id'), 'stock_movimientos', ['almacen_id'], unique=False)
    op.create_index(op.f('ix_stock_movimientos_empresa_id'), 'stock_movimientos', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_stock_movimientos_producto_id'), 'stock_movimientos', ['producto_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_movimientos_producto_id'), table_name='stock_movimientos')
    op.drop_index(op.f('ix_stock_movimientos_empresa_id'), table_name='stock_movimientos')
    op.drop_index(op.f('ix_stock_movimientos_almacen_id'), table_name='stock_movimientos')
    op.drop_table('stock_movimientos')
    op.drop_index(op.f('ix_productos_empresa_id'), table_name='productos')
    op.drop_table('productos')
    op.drop_index(op.f('ix_almacenes_empresa_id'), table_name='almacenes')
    op.drop_table('almacenes')
    # ### end Alembic commands ###
